#!/bin/bash

#包含公用头文件， source 命令
# pinfo perror, enter work directory, $code_name
. ./lazy.h.sh $1



#work directory
mkdir -p .download
cd .download

#====================
#fix possible ld can not found lc

sudo apt-get install libtool-ltdl*

################################
# setup the sources.list of apt
pstart  设置软件源......

backup /etc/apt/sources.list  || _check
#genarate new source list for this code name  ##may not work!
#cat base-sources-hardy.list | sed  "s/hardy/$code_name/g" > sources.list || _check

#sudo cp  sources.list /etc/apt/sources.list
pstatus
#################################
pstart "add ppa vbox sources ....."
sudo add-apt-repository ppa:debfx/virtualbox 
pstatus

#################
pstart "add medibuntu asc"
wget-tarball http://packages.medibuntu.org/pool/free/m/medibuntu-keyring/medibuntu-keyring_2008.04.20.tar.gz
cd medibuntu-keyring-2008.04.20 || _check
cd keyrings || _check
srun gpg --import medibuntu-keyring.gpg || _check
cd ..
cd ..
sudo wget http://www.medibuntu.org/sources.list.d/hardy.list --output-document=/etc/apt/sources.list.d/medibuntu.list
sudo aptitude update 
srun sudo aptitude remove -y medibuntu-keyring 
sudo apt-get install  -y --force-yes medibuntu-keyring || _check


### add smplayer sources list
sudo add-apt-repository ppa:medibuntu-maintainers/ppa
sudo add-apt-repository ppa:rvm/smplayer
pstatus

#############winehq
wget -q http://wine.budgetdedicated.com/apt/387EE263.gpg -O- | sudo apt-key add -
sudo wget http://wine.budgetdedicated.com/apt/sources.list.d/hardy.list -O /etc/apt/sources.list.d/winehq.list


##################################
# basic crack of dash ==> bash
# ubuntu shell problem  
pinfo  "处理sh:替换dash为bash......"

#ls -l /bin/sh
#sudo update-alternatives --config sh
sudo rm -f --verbose /bin/sh  || _check

srun sudo update-alternatives --verbose --install /bin/sh sh /bin/dash 10  || _check
#sudo update-alternatives --display sh
srun sudo update-alternatives --verbose --install /bin/sh sh /bin/bash 40  || _check
sudo update-alternatives --display sh  || _check
#sudo update-alternatives --config sh

#lack of arch command
sudo cp ../arch /bin/  || _check
pstatus
#################################
pstart  更新软件源......
srun sudo apt-get update 

pinfo "初始化完成"


