#!/bin/bash

#包含公用头文件， source 命令
# pinfo perror, enter work directory, $code_name
. ./lazy.h.sh $1



#====================
#fix possible ld can not found lc
pstart  "basic setup "
srun sudo apt-get install -y --force-yes libtool  libltdl-dev
#pae support
srun sudo apt-get install -y --force-yes linux-image-generic-pae linux-headers-generic-pae
srun sudo apt-get install -y --force-yes build-essential
pinfo done 

################################
# setup the sources.list of apt
pstart  设置软件源......

pstart "add fav ppa sources ....."
srun sudo add-apt-repository ppa:debfx/virtualbox 
srun sudo add-apt-repository ppa:medibuntu-maintainers/ppa
srun sudo add-apt-repository ppa:rvm/smplayer
srun sudo add-apt-repository ppa:ubuntu-wine/ppa
srun sudo add-apt-repository ppa:gnomenu-team/ppa
pstatus


##################################
# basic crack of dash ==> bash
# ubuntu shell problem  
pinfo  "处理sh:替换dash为bash......"

sudo rm -f --verbose /bin/sh  || _check
srun sudo update-alternatives --verbose --install /bin/sh sh /bin/dash 10  || _check
#sudo update-alternatives --display sh
srun sudo update-alternatives --verbose --install /bin/sh sh /bin/bash 40  || _check
sudo update-alternatives --display sh  || _check
#sudo update-alternatives --config sh
########lack of arch command
sudo cp  bin/arch /bin/  || _check
pstatus


#################################
pstart  更新软件源......
srun sudo apt-get update 
pinfo "初始化完成"

pstart "clean kernel images "
srun sudo aptitude purge ~ilinux-image-.*\(\!`uname -r`\)
srun sudo apt-get clean
srun sudo apt-get autoremove
pinfo "done"

exit 



############################stale feature ====================================================================

#############winehq
wget -q http://wine.budgetdedicated.com/apt/387EE263.gpg -O- | sudo apt-key add -
sudo wget http://wine.budgetdedicated.com/apt/sources.list.d/hardy.list -O /etc/apt/sources.list.d/winehq.list



#################
pstart "add medibuntu asc"
wget-tarball http://packages.medibuntu.org/pool/free/m/medibuntu-keyring/medibuntu-keyring_2008.04.20.tar.gz
cd medibuntu-keyring-2008.04.20 || _check
cd keyrings || _check
srun gpg --import medibuntu-keyring.gpg || _check
cd ..
cd ..
sudo wget http://www.medibuntu.org/sources.list.d/hardy.list --output-document=/etc/apt/sources.list.d/medibuntu.list
sudo aptitude update 
srun sudo aptitude remove -y medibuntu-keyring 
sudo apt-get install  -y --force-yes medibuntu-keyring || _check


#backup /etc/apt/sources.list  || _check
#genarate new source list for this code name  ##may not work!
#cat base-sources-hardy.list | sed  "s/hardy/$code_name/g" > sources.list || _check
#sudo cp  sources.list /etc/apt/sources.list
#pstatus


