#!/bin/bash

#########################################################################################################
#define fav packages to install
naultilus=" nautilus  nautilus-gksu   nautilus-open-terminal    nautilus-script-audio-convert \
              nautilus-image-converter  "

ibus="ibus ibus-gtk ibus-pinyin ibus-pinyin-db-open-phrase  ibus-table"

offices="nfs-common ssh ntp "

dict="stardict stardict-gnome stardict-plugin \
             stardict-plugin-espeak stardict-plugin-festival stardict-plugin-gucharmap \
             stardict-plugin-spell stardict-tools "

chat="xchat xchat-gnome "

misc="kdebluetooth  patch guilt unrar  rar tree deluge-torrent alien kate  kdiff3 xchm chmsee  \
                   ksnapshot "

multi_media="k9copy acidrip  gmountiso smplayer"


app_dev="autoconf git-core automake  autotools-dev binutils-dev  \
     bison   comerr-dev   dpkg-dev  flex               \
     g++    gawk  gcc gcc-multilib  gettext  libacl1-dev   \
     linux-libc-dev \
     libreadline5-dev   libtool libxmltok1-dev  \
     linux-libc-dev     m4   mkisofs  patch   pkg-config   rpm  ss-dev  \
     tcl       texi2html texlive-base-bin texlive-common     \
     x11proto-core-dev  zlib1g-dev  "

kernel_dev="build-essential uuid uuid-dev \
              netspeed git-arch git-cvs git-email git-gui   git-svn gitk gitweb \
             tex-common subversion "

languages="language-pack-zh  language-pack-gnome-zh-base   language-pack-zh-base  \
        language-support-input-zh   kde-l10n-zhcn \
           language-pack-kde-zh   language-pack-kde-en language-pack-kde-en-base  thunderbird-locale-zh-cn \
             qt4-qtconfig ttf-arphic-ukai  \
            ttf-arphic-ukai ttf-wqy-zenhei language-support-fonts-zh  openoffice.org-l10n-zh-cn xfonts-wqy"


#########################################################################################################
#包含公用头文件， source 命令
# pinfo perror, enter work directory, $silence
. ./lazy.h.sh $1

#work directory
mkdir -p packages
cd packages

fapt-install-desc "Chinese Simplified internationalized (i18n) base " $languages 
fapt-install-desc "application developer pkgs " $app_dev 
fapt-install-desc "multimedia " $multi_media 
fapt-install-desc "kernel develop pkgs" $kernel_dev
fapt-install-desc "naultius"  $naultilus
fapt-install-desc "ibus"  $ibus
fapt-install-desc "offfice"  $offices
fapt-install-desc "dicts"  $dict
fapt-install-desc "chat"  $chat
fapt-install-desc "misc"  $misc


################################################
# vsftp baiscs
pstart "Installing vsftpd"
srun sudo apt-get install -y vsftpd  || _check
srun sudo  /etc/init.d/vsftpd  start  
sudo mkdir -p /home/ftp  || _check
sudo chmod a+x /home/ftp || _check 
sudo chmod a-w /home/ftp || _check
srun sudo addgroup ftp  
srun sudo adduser ftp ftp --home /hoem/ftp    
sudo  /etc/init.d/vsftpd  restart || _check
pstatus

################################################33
#stardict wordtable
wget-tarball http://jaist.dl.sourceforge.net/sourceforge/stardict/stardict-langdao-ec-gb-2.4.2.tar.bz2
sudo mv stardict-langdao-ec-gb-2.4.2 /usr/share/stardict/dic
wget-tarball http://nchc.dl.sourceforge.net/sourceforge/stardict/stardict-langdao-ce-gb-2.4.2.tar.bz2
sudo mv stardict-langdao-ce-gb-2.4.2 /usr/share/stardict/dic



pstart "last step upgrade them all!"
sudo apt-get upgrade -y
pstatus

pinfo  "ssh 认证key在服务器的存放地点"
pinfo 'cat .ssh/id_dsa.pub | ssh user@remote “cat - >>.ssh/authorized_keys” #将公钥写到服务器'





