#!/bin/bash

#########################################################################################################
#define fav packages to install

multi_media="k9copy acidrip  gmountiso smplayer  ubuntu-restricted-extras xrdp"


naultilus=" nautilus  nautilus-gksu   nautilus-open-terminal    nautilus-script-audio-convert \
              nautilus-image-converter  "

#ibus="ibus ibus-gtk ibus-pinyin ibus-pinyin-db-open-phrase  ibus-table"


kernel_dev="build-essential uuid uuid-dev \
              netspeed git-arch git-cvs git-email git-gui   git-svn gitk gitweb \
             subversion git-core "
             

app_dev="autoconf  automake expect autotools-dev binutils-dev  \
     bison   comerr-dev   dpkg-dev  flex               \
     g++    gawk  gcc gcc-multilib  gettext  libacl1-dev   \
     linux-libc-dev \
       libtool libxmltok1-dev  \
     linux-libc-dev     m4   mkisofs  patch   pkg-config   rpm  ss-dev  \
     tcl       texi2html texlive-base-bin texlive-common     \
     x11proto-core-dev  zlib1g-dev  docbook-xsl-ns doxygen texlive libxml2-dev libxml2-utils  texinfo libexpat1-dev "

Xdev=" x-dev x11proto-xext-dev  xtrans-dev libx11-dev libxext-dev libxinerama-dev xutils-dev libxext-dev "
Netdev=" libcap-dev "

offices="nfs-common ssh ntp wine gedit dnsmasq "

dict="stardict stardict-gnome stardict-plugin \
             stardict-plugin-espeak stardict-plugin-festival stardict-plugin-gucharmap \
             stardict-plugin-spell stardict-tools "

chat="xchat xchat-gnome "

misc="kdebluetooth  patch guilt unrar  rar p7zip p7zip-full p7zip-rar tree deluge-torrent alien kate  kdiff3 xchm chmsee  \
                   ksnapshot "


languages="qt4-qtconfig ttf-arphic-ukai  ttf-arphic-ukai ttf-wqy-zenhei xfonts-wqy"


#########################################################################################################
#包含公用头文件， source 命令
# pinfo perror, enter work directory, $silence
. ./lazy.h.sh $1


#work directory
mkdir -p packages
cd packages

fapt-install-desc "Chinese Simplified internationalized (i18n) base " $languages 
fapt-install-desc "application developer pkgs " $app_dev $Xdev $Netdev 
fapt-install-desc "multimedia " $multi_media 
fapt-install-desc "kernel develop pkgs" $kernel_dev
fapt-install-desc "naultius"  $naultilus
#fapt-install-desc "ibus"  $ibus
fapt-install-desc "offfice"  $offices
fapt-install-desc "dicts"  $dict
fapt-install-desc "chat"  $chat
fapt-install-desc "misc"  $misc

########## gedit chinese auto detect 
srun gconftool-2 --set /apps/gedit-2/preferences/encodings/auto_detected "[UTF-8,CURRENT,GB18030,BIG5,ISO-8859-15,UTF-16]" --type list --list-type string

################################################
# vsftp baiscs
ftp_home="/home/ftp"

pstart "Installing vsftpd"
srun sudo apt-get install -y vsftpd  || _check
srun sudo  /etc/init.d/vsftpd  start  
sudo mkdir -p $ftp_home  || _check
sudo chmod a+x $ftp_home || _check 
sudo chmod a-w $ftp_home || _check
srun sudo addgroup ftp  
srun sudo adduser ftp ftp --home  $ftp_home    
sudo  /etc/init.d/vsftpd  restart || _check
pstatus

################################################33
#stardict wordtable
cd /tmp
sudo mkdir -p /usr/share/stardict/dic

wget-tarball http://pkgs.fedoraproject.org/repo/pkgs/stardict-dic/stardict-langdao-ce-gb-2.4.2.tar.bz2/8e9700798a0ffeed23207b7cf2592246/stardict-langdao-ce-gb-2.4.2.tar.bz2
wget-tarball http://pkgs.fedoraproject.org/repo/pkgs/stardict-dic/stardict-langdao-ce-gb-2.4.2.tar.bz2/8e9700798a0ffeed23207b7cf2592246/stardict-langdao-ce-gb-2.4.2.tar.bz2 

sudo mv stardict-langdao-ec-gb-2.4.2 /usr/share/stardict/dic
sudo mv stardict-langdao-ce-gb-2.4.2 /usr/share/stardict/dic
cd -


pstart "last step upgrade them all!"
sudo apt-get upgrade -y
pstatus

pinfo  "ssh 认证key在服务器的存放地点"
pinfo 'cat .ssh/id_dsa.pub | ssh user@remote “cat - >>.ssh/authorized_keys” #将公钥写到服务器'





